source 'https://github.com/CocoaPods/Specs.git'

target 'SKKeyboardResigner', :exclusive => true do
  pod "SKKeyboardResigner", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SKKeyboardResigner", :path => "../"  
end
